### ISSUE TITLE
Make error

### ISSUE THREAD

**Issue by Crimbo** [skyhover/Deckard#1]
Error starts at line...

"make[1]: execvp: ./mainc.py: Permission denied"

and then ends at...

"make: **\* No rule to make target `../ptgen/gcc/gccptgen.a', needed by`cvecgen'. Stop."

**Comment by ghost** [comment]
Solved: All files need to be set to execute, before 'build.sh' can be run.

**Comment by skyhover** [comment]
Set the permission...and install python...

**Comment by ziad-halabi9** [comment]
I am having the same error: ""make: **\* No rule to make target ../ptgen/gcc/gccptgen.a', needed bycvecgen'. Stop.""

Can you please elaborate more on the solution? 
Thank you!

**Comment by ryanlr** [comment]
I have the same problem with ziad-halabi9. Can anyone help please?
