### ISSUE TITLE
On Bugfiltering

### ISSUE THREAD

**Issue by Crimbo** [skyhover/Deckard#3]
Ln 52 scripts/bugfiltering
filterpath = os.environ.get("DECKARD_DIR")

The bash crashes, stating it cannot find the Deckard path.

**Comment by ghost** [comment]
Quick fix:
filterpath = 'path/to/Deckard'

The path has ' ' wrapped around it, so the variable can be saved as a string, and can be used elsewhere in the file.

**Comment by skyhover** [comment]
You can do this, but "bugfiltering" is more like an intermediate file. It's better to run "deckardd.sh" instead; it would tell you to set the env variables via "config" in the same way as the clone detection part.
