### ISSUE TITLE
Build on Linux fails

### ISSUE THREAD

**Issue by Testeriono** [skyhover/Deckard#7]
Hi
I am trying to compile Deckard on a Linux system, but it stops, because it tries to find "dot2d".
Is this some kind of third party lib I should add? If so were should it be placed?

Here is a part of the log:

Everything cool above here:
- -c -O3 -DREAL_FLOAT  enumBuckets.cpp
  g++ -o ../bin/enumBuckets -O3 enumBuckets.o BucketHashing.o Geometry.o LocalitySensitiveHashing.o Random.o Util.o GlobalVars.o SelfTuning.o NearNeighbors.o -lm
  g++ -c -O3 -DREAL_FLOAT  exploreBuckets.cpp
  g++ -o ../bin/exploreBuckets -O3 exploreBuckets.o BucketHashing.o Geometry.o LocalitySensitiveHashing.o Random.o Util.o GlobalVars.o SelfTuning.o NearNeighbors.o -lm
  make[1]: Leaving directory `/home/janO/Deckard/src/lsh/sources'
  ./build.sh: Zeile 98: cd: ../lib: Datei oder Verzeichnis nicht gefunden (File or Folder not found)
  ./build.sh: Zeile 111: cd: ../dot2d/grammars/output: Datei oder Verzeichnis nicht gefunden (File or Folder not found)
  ./build.sh: Zeile 123: cd: ../dot2d: Datei oder Verzeichnis nicht gefunden (File or Folder not found)

In braces I translated the error from German to English.

Cheers and Thanks

**Comment by skyhover** [comment]
Hi, yes, dot2d is a third-party library used intermediately for experiments.
Are you using the latest version from the repository?
The issue was fixed in 2013/03.

Cheers!
